### ISSUE TITLE
Apple Clone issue

### ISSUE THREAD

**Issue by abongsjoel** [rebeccayilma/Apple_clone#1]
This issue is created for a peer-to-peer code review for one of the team members of Team 161

**Comment by MrkarlosM** [comment]
Don't forget to use the correct specification for colors in Hex:

`#1f94d1` instead of `#1F94D1`.

It's a good habit to not use words like `flex` , `display`  or `position`  in the classes name:

`class="flex  flex-center-column flex-center-row"`

That may lead to confusion when working remotely.

**Comment by abongsjoel** [comment]
On line 47 of your css, use small letters for the hexadecimal color values e.g. #e0e6eC instead of #E0E6EC;

In your HTML lines 37 to 42, your alt attribute should be more descriptive instead just saying banner to everything, try to describe what each image contains

**Comment by abongsjoel** [comment]
CSS line 81 could benefit from a shortform 
```
padding: 0 0.5em;
```
would give the same result as 
```
padding: 0 0.5em 0 0.5em;
```
